Vagrant.configure(2) do |config| 
    config.vm.box = "bento/ubuntu-22.04" 
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v| 
        v.gui = false
        v.cpus = "1"
        v.memory = "1024"
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end

    config.vm.define "nfss" do |nfss|
        nfss.vm.network "private_network", ip: "192.168.50.10",  virtualbox__intnet: "net1"
        nfss.vm.hostname = "nfss"
    end

    config.vm.define "nfsc" do |nfsc| 
        nfsc.vm.network "private_network", ip: "192.168.50.11",  virtualbox__intnet: "net1" 
        nfsc.vm.hostname = "nfsc"
    end
end 

