Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "./shared", "/shared", disabled: true
    config.vm.provider "virtualbox" do |vms|
        # vms.gui = false
        vms.check_guest_additions = false
        vms.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
    
    config.vm.define "domain-controller" do |dc|
        dc.vm.box = "gusztavvargadr/windows-server"
        dc.vm.network "public_network", ip: "192.168.1.11", bridge: "wlp2s0"
        dc.vm.hostname = "domain-controller"
        dc.vm.provider "virtualbox" do |vm1|
            vm1.memory = "2048"
            vm1.cpus = "2"
        end

        # script
        # victim.vm.provision "shell", path: "script.sh"

        # shell
        # victim.vm.provision "shell", inline: <<-SHELL
        # SHELL

        # ansible
        # victim.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
end