Vagrant.configure("2") do |config|
    config.vm.network "public_network", ip: "192.168.1.10", bridge: "wlp2s0"
    config.vm.hostname = "dc"
    config.vm.box = "gusztavvargadr/windows-server"
    config.vm.provider "virtualbox" do |v|
        v.cpus = "2"
        v.memory = "2048"
    end
    # #script
    # config.vm.provision "shell", path: "script.sh"

    # #shell
    # config.vm.provision "shell", inline: <<-SHELL
    # SHELL

    # #ansible
    # config.vm.provision "ansible" do |ansible|
    #     ansible.verbose = "vv"
    #     ansible.playbook = "provision/playbook.yml"
    #     ansible.become = "true"
    # end
end