Vagrant.configure(2) do |config| 
    config.vm.box = "bento/ubuntu-22.04" 
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v| 
        v.gui = false
        v.cpus = "1"
        v.memory = "1024"
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
  
    config.vm.define "nginx" do |nginx|
        nginx.vm.network "public_network", ip: "192.168.1.39", bridge: "en0: Wi-Fi"
        nginx.vm.hostname = "nginx"
        # host1.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
  end