Vagrant.configure("2") do |config|
    config.vm.network "public_network"
    config.vm.box = "gusztavvargadr/windows-server"
    config.vm.provider "virtualbox" do |v|
        v.cpus = "2"
        v.memory = "2048"
    end
end
