MACHINES = {
    :"raid" => {
        :box_name => "bento/ubuntu-22.04",
        :cpus => 1,
        :memory => 1024,
        :disks => {
            :sas1 => {
                :dfile => './sas1.vdi',
                :size => 250,
                :port => 1
            },
            :sas2 => {
                :dfile => './sas2.vdi',
                :size => 250,
                :port => 2
            },
            :sas3 => {
                :dfile => './sas3.vdi',
                :size => 250,
                :port => 3
            },
            :sas4 => {
                :dfile => './sas4.vdi',
                :size => 250,
                :port => 4
            },
            :sas5 => {
                :dfile => './sas5.vdi',
                :size => 250,
                :port => 5
            }
	    }
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: false
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
                needsController = false
                boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                        needsController =  true
                    end
                end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SAS", "--add", "sas" ]
                    boxconfig[:disks].each do |dname, dconf|
                       vb.customize ['storageattach', :id,  '--storagectl', 'SAS', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
            end
            # config.vm.provision "shell", inline: <<-SHELL
            # /vagrant/raid.sh
            # SHELL
        end
    end
end