MACHINES = {
    :"mdadm" => {
        :box_name => "bento/ubuntu-22.04",
        :cpus => 1,
        :memory => 1024,
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: false
        # config.vm.provision "shell", inline: <<-SHELL
        # SHELL
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end
        end
    end
end