---
- name: Install Nginx
  hosts: host1
  become: true
  gather_facts: true
  vars_files:
    - variables.yml

  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install Required Packages
      ansible.builtin.apt:
        pkg: "{{ pkgs }}"
    - name: Add Nginx Repo Key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
    - name: Add Nginx Repo
      ansible.builtin.apt_repository:
        repo: "deb http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"
        state: present
        update_cache: true
    - name: Install Nginx
      ansible.builtin.apt:
        pkg: nginx
        state: present