---
- name: NGINX
  hosts: host1
  become: true
  gather_facts: false

  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: install nginx
      ansible.builtin.apt:
        pkg: nginx
        state: present