---

- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
    - name: main packages
      ansible.builtin.apt:
        pkg: net-tools
        state: present

#   # runs only on host1
- hosts: host1
  become: true
  gather_facts: false
  tasks:
    - name: nginx
      ansible.builtin.apt:
        pkg: nginx
        state: absent

  # runs only on host2
- hosts: host2
  become: true
  gather_facts: false
  tasks:
    - name: docker
      ansible.builtin.apt:
        pkg: docker.io
        state: absent
