---
- name: install Nginx
  hosts: frontend
  become: true
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
    - name: remove nginx
      ansible.builtin.apt:
        pkg: nginx
        state: absent