---
- name: Nginx
  hosts: nginx
  become: true
  gather_facts: false
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: NGINX | Cache Update
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: NGINX | Install Nginx
      apt:
        pkg: nginx
        state: present
      notify:
        - restart nginx
    - name: NGINX | Create Nginx config from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
  
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded