---

- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
    - name: main packages
      ansible.builtin.apt:
        pkg: net-tools
        state: present

  # runs only on host1
- hosts: host1
  become: true
  gather_facts: false
  tasks:
    - name: nginx
      ansible.builtin.apt:
        pkg: nginx
        state: present

  # runs only on host2
  # - name: install Nginx
  #   hosts: host2
  #   tasks: