Vagrant.configure(2) do |config| 
    config.vm.box = "bento/ubuntu-22.04" 
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v| 
        v.gui = false
        v.cpus = "1"
        v.memory = "1024"
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
  
    config.vm.define "host1" do |host1|
        host1.vm.network "private_network", ip: "192.168.50.10",  virtualbox__intnet: "vagrant-net"
        host1.vm.hostname = "host1"
        # script
        # host1.vm.provision "shell", path: "script.sh"
        
        # shell
        # host1.vm.provision "shell", inline: <<-SHELL
        # SHELL
        
        # ansible 
        # host1.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
  
    config.vm.define "host2" do |host2| 
        host2.vm.network "private_network", ip: "192.168.50.11",  virtualbox__intnet: "vagrant-net" 
        host2.vm.hostname = "host2"
  
        # script
        # host2.vm.provision "shell", path: "script.sh"
        
        # shell
        # host2.vm.provision "shell", inline: <<-SHELL
        # SHELL
  
        # ansible
        # host2.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
  end 