MACHINES = {
    :"kernel-update" => {
        :box_name => "generic/centos8",
        :cpus => 1,
        :memory => 1024,
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.provision "shell", inline: <<-SHELL
            sudo yum install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
            sudo yum --enablerepo elrepo-kernel install kernel-ml -y
            sudo reboot
        SHELL
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end
        end
    end
end