Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.hostname = "packages"
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.cpus = "1"
        v.memory = "1024"
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
end